name: The Creative Feminine
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf482'
    - '#3d0505'
    - '#972048'
    - '#4f8259'
    - '#e0764e'
  brandStrength: 0.5406608525663614
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
