name: The Creative Feminine
favicon: null
layout_spectrum: 0.29491034196689725
typography_spectrum: 0.8705465116072446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5406608525663614
  lightness: 0.5294691217131913
  saturation: 0.05961342970840633
  rhythmicContrast: 0.23360522068105638
purpose: []
